### Numpy Introduction
* Numeric Python is a library for managing large data sets

In [30]:
# by convention we import necessary stuff in the first cell
import numpy as np
# from mymodule import stuff

In [ ]:
a=3
b=7
a/b # this uses __repr__
print(b/a) # uses __str__

In [29]:
# python will remember the result of any code that has already beeen executed
a**b

2187

In [ ]:
c = 'oops'

In [28]:
c*3

'oopsoopsoops'

#### Using Basic Numpy


In [39]:
# numpy offers additional data structures beyond those available in Python
# array range (arange)
# start, stop-before, step
n = np.arange(3.0,12.5,0.5) # all the members must be of the same data type
n
n.dtype

dtype('float64')

In [ ]:
m = np.arange('a', 'b', 'c') # fix this <------------
m # throws an exception

In [90]:
# we can use many-dimensions in our arrays
# we have a mutable collection of one data type
d = np.random.randn(9,3) # we have an array of 9 by 3 random values
# d = np.random.randn(900,300) # we have an array of 900 by 300 random values
d.dtype
d.shape # (9, 3)
d

array([[ 0.74940391, -0.99453298,  0.11878492],
       [-0.03727387, -0.363663  ,  0.76145011],
       [-0.52633462, -0.10539164, -0.68450957],
       [ 0.24177038,  0.69260389,  1.03848707],
       [ 0.75081109, -0.7189879 ,  2.47873692],
       [ 0.29694102,  1.47248013,  0.38286765],
       [-1.80151384,  0.48370372,  0.64778941],
       [-1.90383446,  1.19474201, -0.20795697],
       [-1.27367964,  0.42320689,  0.45410376]])

In [51]:
# multi dimensional arrays
e =np.random.randn(2,3,2,5,2,3)
e # e.shape, e.dtype

array([[[[[[ 3.31092128e-02, -1.60356946e-01,  3.27008623e+00],
           [ 3.14016086e-01,  1.45443745e+00, -2.61176922e-01]],

          [[ 6.55891313e-01, -1.16668860e+00,  2.89458565e-01],
           [-1.87022795e+00,  5.90160084e-02, -2.89468814e+00]],

          [[ 2.38198571e-01, -1.59799890e+00,  3.53199718e-01],
           [ 1.54352451e+00,  1.16279199e+00, -1.14066407e+00]],

          [[-8.39944505e-01,  9.80954578e-01,  3.43347078e-01],
           [ 9.95245505e-01,  9.04245939e-01,  2.05094788e+00]],

          [[ 2.87696571e-01, -2.13048234e+00, -8.95619691e-02],
           [-1.89032921e+00,  7.87789447e-01,  6.24587721e-01]]],


         [[[ 3.17562843e-01,  1.46741003e-01, -6.57862626e-01],
           [ 8.73935816e-01, -8.15977326e-01, -8.78074269e-01]],

          [[-9.98967232e-01, -2.19056804e+00, -4.54600967e-01],
           [ 4.90827076e-01,  4.10721576e-01, -5.51861219e-01]],

          [[ 9.74450322e-01, -2.81056263e-01, -1.35404881e-01],
           [-1.21676383e

In [66]:
# Creating arrays
f = np.zeros( (3,6) ) # careful: n.empty() will NOT zero-out the memory
f.dtype # we have floats

dtype('float64')

In [55]:
f

array([[1.37962049e-306, 1.24610791e-306, 1.11260959e-306],
       [1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
       [1.78019082e-306, 4.45061456e-308, 1.24612081e-306],
       [1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
       [1.78019625e-306, 1.11255866e-306, 8.90098127e-307],
       [9.34609790e-307, 3.91792279e-317, 8.34402697e-308]])

In [69]:
s = d.astype(np.str_) # this is numpy syntax
s.dtype

dtype('<U32')

In [71]:
i = f.astype(np.int32) # typically int32 or int64
i

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#### Calculations on Arrays

In [81]:
z = np.zeros((3,3,3))
((z+3)**2) # extremely performant
# z # remember the original data set is usually unchanged by operations

array([[[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]],

       [[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]],

       [[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]]])

In [98]:
# we can carry out complex operations
(d-2)*0.5/b**100

array([[-1.9332279660808942e-85, -4.629084437932332e-85,
        -2.908067303923953e-85],
       [-3.149310035069743e-85, -3.6538571103930145e-85,
        -1.914606410618575e-85],
       [-3.9053222628367375e-85, -3.254609574170327e-85,
        -4.149836241128568e-85],
       [-2.717950818446151e-85, -2.021032000784183e-85,
        -1.4863501589689602e-85],
       [-1.9310526783742804e-85, -4.203134398756016e-85,
        7.400531760578345e-86],
       [-2.6326655505122393e-85, -8.154640546500568e-86,
        -2.4998362803726984e-85],
       [-5.876551943978113e-85, -2.343959338599536e-85,
        -2.0903082586384313e-85],
       [-6.034723778068238e-85, -1.2448042020009668e-85,
        -3.4131596884614897e-85],
       [-5.060601976587696e-85, -2.4374780647105186e-85,
        -2.389716293905904e-85]], dtype=object)

### Accessing Members
we can use slicing in any data structure

In [104]:
d[0:5] # start:stop-before:step

array([[ 0.74940391, -0.99453298,  0.11878492],
       [-0.03727387, -0.363663  ,  0.76145011],
       [-0.52633462, -0.10539164, -0.68450957],
       [ 0.24177038,  0.69260389,  1.03848707],
       [ 0.75081109, -0.7189879 ,  2.47873692]])

In [105]:
d[0:5:2] 

array([[ 0.74940391, -0.99453298,  0.11878492],
       [-0.52633462, -0.10539164, -0.68450957],
       [ 0.75081109, -0.7189879 ,  2.47873692]])

In [109]:
d[::-1] # assume [0:end]

array([[-1.27367964,  0.42320689,  0.45410376],
       [-1.90383446,  1.19474201, -0.20795697],
       [-1.80151384,  0.48370372,  0.64778941],
       [ 0.29694102,  1.47248013,  0.38286765],
       [ 0.75081109, -0.7189879 ,  2.47873692],
       [ 0.24177038,  0.69260389,  1.03848707],
       [-0.52633462, -0.10539164, -0.68450957],
       [-0.03727387, -0.363663  ,  0.76145011],
       [ 0.74940391, -0.99453298,  0.11878492]])

In [116]:
d[1,1]=0 # we can access members (NB actual value may be more precise than presented value)
d[1]=9 # the entire row. NB arrays are mutable
d

array([[ 0.74940391, -0.99453298,  0.11878492],
       [ 9.        ,  9.        ,  9.        ],
       [-0.52633462, -0.10539164, -0.68450957],
       [ 0.24177038,  0.69260389,  1.03848707],
       [ 0.75081109, -0.7189879 ,  2.47873692],
       [ 0.29694102,  1.47248013,  0.38286765],
       [-1.80151384,  0.48370372,  0.64778941],
       [-1.90383446,  1.19474201, -0.20795697],
       [-1.27367964,  0.42320689,  0.45410376]])

In [118]:
d.shape
d.T # transpose the array members

array([[ 0.74940391,  9.        , -0.52633462,  0.24177038,  0.75081109,
         0.29694102, -1.80151384, -1.90383446, -1.27367964],
       [-0.99453298,  9.        , -0.10539164,  0.69260389, -0.7189879 ,
         1.47248013,  0.48370372,  1.19474201,  0.42320689],
       [ 0.11878492,  9.        , -0.68450957,  1.03848707,  2.47873692,
         0.38286765,  0.64778941, -0.20795697,  0.45410376]])