## Saving and Loading External Data

In [1]:
import numpy as np
import pandas as pd

In [3]:
arr = np.arange(10)
arr
np.save('my_array', arr) # this will persistt the array in a file called my_arr.npy
np.savez('my_archive', arr)

In [6]:
# read back
arr2 = np.load('my_array.npy')
arr2
arr3 = np.load('my_archive.npz') # a zipped archive
arr3 # this is the archive file as a compressed asset

In [20]:
# we can provide a random seed
np.random.seed(20) # gives repeatable results
r = np.arange(10)
np.random.shuffle(r)
r

array([7, 1, 8, 5, 0, 2, 6, 9, 4, 3])

In [25]:
# we can save as a csv
np.savetxt('my_r.csv', r, delimiter=',') # create a comma separate value file
r

array([7, 1, 8, 5, 0, 2, 6, 9, 4, 3])

In [24]:
# load text
d = np.loadtxt('my_r.csv')
d

array([7., 1., 8., 5., 0., 2., 6., 9., 4., 3.])

In [28]:
# we can load very large data sets from csv
df = pd.read_csv('data/salaries.csv')
df # we have a DataFrame
df.describe() # some stats

phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [36]:
df.columns
df.size
df.sum()
df.max() # or min() std() ...
# we can use dot syntax or [] syntax
df['phd']
df.phd # careful - rank is an operator in pandas

0     56
1     12
2     23
3     40
4     20
      ..
73    18
74    19
75    17
76    28
77    23
Name: phd, Length: 78, dtype: int64

In [39]:
df

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [41]:
# grouping data
# df_rank = df.groupby(['rank']) # this is a list
# df_rank = df.groupby(['sex', 'rank'])
df_rank = df.groupby(['rank', 'sex']) # the order matters

df_rank # we have a group object
df_rank.mean() # or sum, max etc

phd    service         salary
sex    rank                                          
Female AssocProf  15.500000  11.500000   88512.800000
       AsstProf    5.636364   2.545455   78049.909091
       Prof       23.722222  17.111111  121967.611111
Male   AssocProf  13.666667  10.666667  102697.666667
       AsstProf    4.250000   1.750000   85918.000000
       Prof       29.214286  24.178571  124690.142857

In [43]:
# challenge: find the mean salary and service for each rank
l = ['salary', 'service']
gb = df.groupby('rank')
gb[l].mean()

salary    service
rank                               
AssocProf   91786.230769  11.307692
AsstProf    81362.789474   2.210526
Prof       123624.804348  21.413043

In [48]:
# mini challenge: show the mean salary for each rank by male/female
df.groupby(['rank', 'sex']).mean()
# mini challenge: mean salary where salary exceeds 120000
df_subset = df[ df['salary']>120000 ]
df_subset.groupby(['rank']).mean()

phd  service    salary
rank                         
Prof  28.8     24.6  141722.4

### Aggregate Data

In [52]:
# we can aggregate data members
df.agg({'rank':['nunique']}) # very handy to count unique occurences

rank
nunique     3

In [67]:
# show the minima from all the data, but just which rank this belongs to
# df[['sex','rank','phd','salary']].agg(['min', 'max', 'mean'])
df[['phd','salary']].agg(['min', 'max', 'mean']) # only numeric values

phd         salary
min    1.000000   57800.000000
max   56.000000  186960.000000
mean  19.705128  108023.782051